### ISSUE TITLE
Two forward-slashes in @import in css seems to break indention

### ISSUE THREAD

**Issue by KudaSai** [fxbois/web-mode#653]
When you add an import statement to the beginning of a .css file which contains to forward-slashes, web-mode interprets that as a comment and indents the remainder of the file.

```CSS
@import url('https://fonts.googleapis.com/css?family=Merriweather');

  body {
    margin: 0;
    padding: 0;
  }
```
Here the body element should be completely to the left but is indented instead.

I'm pretty sure this has to do with the // in the import statement because if I escape the first one everything works (and so does the CSS):

```CSS
@import url('https:\//fonts.googleapis.com/css?family=Merriweather');

body {
  margin: 0;
  padding: 0;
}
```
I don't know if this is a bug and whether it's worth the effort of fixing (escaping works) but at least you know!

Thanks for web-mode and a happy new year!
